version: "3.9"
services:
  mysql:
    image: mysql:8.0.22
    restart: always
    command: "--default-authentication-plugin=mysql_native_password"
    environment:
      MYSQL_ROOT_PASSWORD: epitech
      MYSQL_DATABASE: kiloupabocou
      MYSQL_USER: reyesvictor
      MYSQL_PASSWORD: epitech
    ports: [3306:3306]
    networks: [mysql]
  php:
    build:
        context: .
        dockerfile: docker/php/Dockerfile
        args: 
            - "SYMFONY_PATH=${SYMFONY_PATH}"
    restart: always
    volumes:
        - "./symfony:${SYMFONY_PATH}"
        - "./logs/symfony:${SYMFONY_PATH}/var/log"
    user: 1000:1000
    ports: [9000:9001]
    depends_on: [mysql]
    networks: [mysql, site]
  nginx:
    image: nginx:1.19.0-alpine
    restart: always
    volumes:
      - "./symfony/public/:${SYMFONY_PATH}"
      - "./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro"
      - "./logs/nginx:/var/log/nginx"
    ports: [80:80]
    depends_on: [php]
    networks: [site]
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: "3306"
    ports: [8080:80]
    depends_on: [mysql]
    networks: [mysql]

networks:
  mysql:
  site:
