version: "3.9"
services:
  #   php:
  #     container_name: symfony
  #     build:
  #       context: .
  #       dockerfile: docker/php/Dockerfile
  #     restart: on-failure
  #     env_file:
  #       - .env
  #     depends_on:
  #       - mysql
  #     user: 1000:1000
  #     ports:
  #       - 9000:9000
  #     networks:
  #       - mysql
  #     volumes:
  #       - ./apps/my-symfony-demo/:/usr/src/app
  #       # - ./logs:/var/log
  #       - db_data:/var/log

  #   nginx:
  #     image: nginx:1.19.0-alpine
  #     container_name: webserver
  #     restart: on-failure
  #     ports:
  #       - 80:80
  #     depends_on:
  #       - php
  #     networks:
  #      - site
  #     volumes:
  #       - ./apps/my-symfony-demo/public/:/usr/src/app
  #       - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

  #   mysql:
  #     image: mysql:8.0
  #     container_name: mysql
  #     command: [--default-authentication-plugin=mysql_native_password]
  #     restart: always
  #     environment:
  #       MYSQL_ROOT_PASSWORD: epitech
  #       MYSQL_DATABASE: kiloupabocou
  #       MYSQL_USER: reyesvictor
  #       MYSQL_PASSWORD: epitech
  #     ports:
  #       - 3306:3306
  #     networks:
  #      - mysql
  #     volumes:
  #       - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
  #       # - ./database/data:/var/lib/mysql
  #       - db_data:/var/lib/mysql

  # networks:
  #   mysql:
  #   site:
  # volumes:
  #   db_data:

  mysql:
    image: mysql:8.0.22
    restart: always
    command: "--default-authentication-plugin=mysql_native_password"
    environment:
      MYSQL_ROOT_PASSWORD: epitech
      MYSQL_DATABASE: kiloupabocou
      MYSQL_USER: reyesvictor
      MYSQL_PASSWORD: epitech
    ports: [3306:3306]
    networks: [mysql]
  php:
    # build: docker/php
    build:
        context: .
        dockerfile: docker/php/Dockerfile
    restart: always
    volumes:
    #   - ./logs/my-symfony-app:/var/www/my-symfony-demo/var/log:cached
      - './symfony/:/usr/src/app'
    user: 1000:1000
    ports: [9000:9001]
    depends_on: [mysql]
    networks: [mysql, site]
  nginx:
    image: nginx:1.19.0-alpine
    restart: always
    volumes:
      - './symfony/public/:/usr/src/app'
      - './docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro'
    ports: [80:80]
    depends_on: [php]
    networks: [site]
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: "3306"
    ports: [8080:80]
    depends_on: [mysql]
    networks: [mysql]

networks:
  mysql:
  site:
# services:
#   mysql:
#     image: mysql:8.0
#     restart: on-failure
#     environment:
#       MYSQL_ROOT_PASSWORD: epitech
#       MYSQL_DATABASE: kiloupabocou
#       MYSQL_USER: reyesvictor
#       MYSQL_PASSWORD: epitech
#   php:
#     build:
#       context: .
#       dockerfile: docker/php/Dockerfile
#     volumes:
#       - ./apps/my-symfony-app/:/usr/src/app
#     restart: on-failure
#     user: 1000:1000
#   nginx:
#     image: nginx:1.19.0-alpine
#     restart: on-failure
#     volumes:
#       - ./apps/my-symfony-app/public/:/usr/src/app
#       - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
#     ports:
#       - 80:80
#     depends_on:
#       - php
#   adminer:
#     image: adminer
#     restart: always
#     ports:
#       - 8080:8080
